version: "3"
services:

    redis-cluster-6380:
        image: redis
        container_name: node-80
        network_mode: "host"
        restart: always
        ports:
            - "6380:6380"
        volumes:
            - ./conf/redis-6380.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-6381:
        image: redis
        container_name: node-81
        network_mode: "host"
        restart: always
        ports:
            - "6381:6381"
        volumes:
            - ./conf/redis-6381.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-6383:
        image: redis
        container_name: node-83
        network_mode: "host"
        restart: always
        ports:
            - "6383:6383"
        volumes:
            - ./conf/redis-6383.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-6384:
        image: redis
        container_name: node-84
        network_mode: "host"
        restart: always
        ports:
            - "6384:6384"
        volumes:
            - ./conf/redis-6384.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-6385:
        image: redis
        container_name: node-85
        network_mode: "host"
        restart: always
        ports:
            - "6385:6385"
        volumes:
            - ./conf/redis-6385.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-6386:
        image: redis
        container_name: node-86
        network_mode: "host"
        restart: always
        ports:
            - "6386:6386"
        volumes:
            - ./conf/redis-6386.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"